---
title: "Usage"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Usage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

_This package is under heavy development. Please do not use this package for actual reserach._

```{r setup, eval =F}
library(sumR)
```

First we load up some example data. Here we have 4 injection of which 1 is a blank sample, all with negative polarity. These files have spectra which are combined together and centroided. 
```{r files, eval =F}
dir <- file.path(r"(F:\stem_cell_blank_cell_samples)")
```

## Full pipeline

```{r eval = F}
exp <- rawToMzml(dir, output = file.path(getwd(), "test2"), rt = c(60, 420))
```

```{r eval = F}
file <- r"(C:\Users\Pascal Maas\Documents\GitHub\sum-r\scripts\2021_09_11_pilot study sampling.xlsx)"
df <- openxlsx::read.xlsx(file, sheet = 1)
df
```

```{r, eval = F}


f <- list.files(dir, full.names = T, pattern = ".mzML")
type <- rep("SAMPLE", length(f))
type[grep("blank", basename(f))] <- "BLANK"
df <- data.frame(Type = type)


exp <- peakPicking(f) %>%
  binSpectra() %>%
  binCells(cellData = df) %>%
  imputation() %>%
  isotopeTagging(assay = "Imputed") %>%
  shapiroTest(assay = "Imputed") %>%
  leveneTest(classifiers = "Type", assay = "Imputed") %>%
  foldChange(classifiers = "Type", assay = "Imputed") %>%
  welchTest(classifiers = "Type", assay = "Imputed")
```



## Data inspection
### PCA
```{r pca, eval = F}
samplePCA(exp, "Imputed")
```

```{r aaa}
compoundPCA(exp, "Imputed")
```

```{r screePCA, eval = F}
screePCA(exp, "Imputed")
```


```{r sessionInfo}
sessionInfo()
```
