image: yufree/xcms

variables:
  GIT_DEPTH: 10
  REPO_NAME: "https://packagemanager.rstudio.com/all/__linux__/focal/latest"
  R_LIBS: "ci/lib"

stages:
  - setup
  - check
  - test
  - pages

before_script:
  - apt-get update
  - apt install -y libcurl4-openssl-dev libssl-dev libxml2-dev libxslt-dev
  - apt install -y libnetcdf-dev libxt-dev qpdf build-essential libglpk40
  - Rscript -e 'install.packages("remotes")'
  - Rscript -e 'install.packages("rcmdcheck")'
  - Rscript -e 'remotes::install_local("sumR", upgrade = "never")'
  - Rscript -e 'remotes::install_cran(c("pkgdown"), upgrade = "never")'
  - Rscript -e 'update.packages(ask = FALSE)'
  - mkdir public

cache:
  key: global-cache
  paths:
      - ${R_LIBS}

setup:
  stage: setup
  script:
    - R -e 'source("ci.R"); ci_setup()'

check:
  stage: check
  script:
    - R -e 'source("ci.R"); ci_check()'

coverage:
  stage: test
  script:
    - R -e 'source("ci.R"); ci_coverage()'
  coverage: '/.*Coverage: (.*)/'

pages:
  stage: pages
  script:
    - Rscript -e 'pkgdown::build_site("sumR")'
    - cp -r sumR/docs/* public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

