# source: https://www.r-bloggers.com/2018/08/gitlab-ci-for-r-package-development/

image: rocker/tidyverse

stages:
  - setup
  - check
  - test

before_script:
  - apt-get update
  - apt install -y libcurl4-openssl-dev libssl-dev libxml2-dev libxslt-dev
  - apt install -y libnetcdf-dev libxt-dev qpdf build-essential libglpk40 libgsl-dev

cache:
  key: one-key-to-rule-them-all
  paths:
    - sumR/cache

setup:
  stage: setup
  script:
    - R -e 'source("ci.R"); ci_setup()'

check:
  stage: check
  script:
    - R -e 'source("ci.R"); ci_check()'

coverage:
  stage: test
  script:
    - R -e 'source("ci.R"); ci_coverage()'
  coverage: '/.*Coverage: (.*)/'

