FROM  bioconductor/bioconductor_docker:RELEASE_3_17-R-4.3.0 AS bioc_base

RUN R -e 'BiocManager::install("mzR")'

FROM bioc_base AS package_base

RUN R -e 'remotes::install_version("dplyr",    version = "1.1.2")'
RUN R -e 'remotes::install_version("ggplot2",  version = "3.4.2")'
RUN R -e 'remotes::install_version("tibble",   version = "3.2.1")'
RUN R -e 'remotes::install_version("tidyr",    version = "1.3.0")'
RUN R -e 'remotes::install_version("pbapply",  version = "1.7-2")'
RUN R -e 'remotes::install_version("devtools", version = "2.4.5")'

FROM package_base

COPY sumR sumR
WORKDIR sumR

RUN R -e 'devtools::document()'
RUN R -e 'devtools::install(dependencies="never")'


### TO BUILD
# docker build . -f Dockerfile-localR -t lacdr/sumr
### TO BUILD without sumR (i.e. to develop it)
# docker build . -f Dockerfile-localR -t lacdr/sumr-dev --target package_base

### TO RUN:
### TO RUN RSTUDIO: user=rstudio, pwd=sumr
# docker run -e PASSWORD=sumr -p 8787:8787 -v .:/home/rstudio/ lacdr/sumr
# Navigate to localhost:8787 in your browser

### TO RUN R terminal:
#[Unix/Mac] docker run --rm -it --name localR -v $(pwd):/local  lacdr/sumr /bin/bash
#[Win?]     docker run --rm -it --name localR -v .:/local  lacdr/sumr /bin/bash

### To enter a running container (use "docker ps" to make sure there is only one)
# docker exec --it localR /bin/bash
#[Unix/Mac] docker exec -it $(docker ps | grep sumr | awk '{print $1}') /bin/bash
